// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd47GGm5eU83Ihp_34jKQvwlMTsusTUhQ',
    appId: '1:284234720950:web:9eab10cd09f72e2474a817',
    messagingSenderId: '284234720950',
    projectId: 'dwell-easy-ghana-e888d',
    authDomain: 'dwell-easy-ghana-e888d.firebaseapp.com',
    storageBucket: 'dwell-easy-ghana-e888d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5VmapSVNJ0PcsVW5TIblw0d4dl4MVmB0',
    appId: '1:284234720950:android:ad9c8f2dea16dbd874a817',
    messagingSenderId: '284234720950',
    projectId: 'dwell-easy-ghana-e888d',
    storageBucket: 'dwell-easy-ghana-e888d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvtDs2NsZG9cyM18T-rdRCS1Y0_Yeojuw',
    appId: '1:284234720950:ios:812036132039133574a817',
    messagingSenderId: '284234720950',
    projectId: 'dwell-easy-ghana-e888d',
    storageBucket: 'dwell-easy-ghana-e888d.firebasestorage.app',
    iosBundleId: 'com.example.dwelleasyGhana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvtDs2NsZG9cyM18T-rdRCS1Y0_Yeojuw',
    appId: '1:284234720950:ios:812036132039133574a817',
    messagingSenderId: '284234720950',
    projectId: 'dwell-easy-ghana-e888d',
    storageBucket: 'dwell-easy-ghana-e888d.firebasestorage.app',
    iosBundleId: 'com.example.dwelleasyGhana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd47GGm5eU83Ihp_34jKQvwlMTsusTUhQ',
    appId: '1:284234720950:web:57d52312d726ca5974a817',
    messagingSenderId: '284234720950',
    projectId: 'dwell-easy-ghana-e888d',
    authDomain: 'dwell-easy-ghana-e888d.firebaseapp.com',
    storageBucket: 'dwell-easy-ghana-e888d.firebasestorage.app',
  );
}
